name: Run Sahibinden Scraper

on:
  schedule:
    - cron: '0 7 * * *'  # Runs every day at 07:00 UTC
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Set Google credentials
        run: echo "${{ secrets.GOOGLE_CREDENTIALS_JSON }}" > credentials.json
      - name: Run scraper
        env:
          GOOGLE_APPLICATION_CREDENTIALS: credentials.json
        run: python scraper.py
